### ISSUE TITLE
describeRoute breaks RPC type inference when strict: true in tsconfig.json

### ISSUE THREAD

**Issue by thecuvii** [rhinobase/hono-openapi#25]
Reproduction link: https://stackblitz.com/edit/stackblitz-starters-6i5fgpsh?file=index.ts

The `describeRoute` function breaks RPC type inference for routes without parameters when strict mode is enabled in tsconfig.json.

**Comment by Blankeos** [comment]
An issue for me as well. :(

Particularly when using `describeRoute({})` middleware. Using `zValidator()` is fine.

**Comment by Blankeos** [comment]
Okay, so this hack does in fact work (https://github.com/rhinobase/hono-openapi/issues/10#issuecomment-2506736426):


```ts
// hono-openapi.d.ts (In your project root)

import type { MiddlewareHandler } from "hono";
import { DescribeRouteOptions } from 'hono-openapi';

declare module "hono-openapi" {
 	export function describeRoute(options: DescribeRouteOptions): MiddlewareHandler;
}
```


Then on tsconfig.

```ts
{
   "compilerOptions": {
      "types": ["./hono-openapi.d.ts]
   }
}
```



I think this makes sense because it does not override the Context types because this has no generics on the `MIddlewareHandler`. Therefore, not affecting the types at all.
I wonder what parts of the DescribeRouteOptions have important generics though.

**Comment by MathurAditya724** [comment]
It seems like the issue was with `hono` types themselves. I just updated the version in this https://github.com/rhinobase/hono-openapi/commit/c7f34e9abd35fc71cbb4ef6702990212fc496c11, and the issue doesn't seem to be happening anymore. I have released a new version `0.3.0`, Can you check if this is still happening at your end?

**Comment by thecuvii** [comment]
The `hono-openapi.d.ts` approach works, but I tested version `0.3.0` in https://stackblitz.com/edit/stackblitz-starters-6i5fgpsh?file=index.ts and the problem still persists in my project.

**Comment by WebDeveloperBen** [comment]
also facing this issue where only the get response returns this:

const fetchResponse: ClientResponse<never, 200, "json">

have tried to modify package versions and the hono-openapi.d.ts fix but no luck

**Comment by MathurAditya724** [comment]
With `v0.3.1`, it seems to be working. Here is a repo, forked from the one shared by @thecuvii but with `v0.3.1` - https://stackblitz.com/edit/stackblitz-starters-mdcctg1d?file=index.ts

**Comment by MathurAditya724** [comment]
Hey, can anyone tell me if this is still happening, or should I close this issue?

**Comment by Blankeos** [comment]
Hi I have checked on:
```jsonc
    "@hono/zod-validator": "^0.4.3",
    "hono": "^4.7.2",
    "hono-openapi": "^0.4.6",
    "zod": "^3.24.2",
    "zod-openapi": "^4.2.3"
```

`describeRoute({})` is definitely not an issue anymore:

### 1. Definition  ✅
<img width="710" alt="Image" src="https://github.com/user-attachments/assets/4212136c-df76-49ab-b516-f5d7f1207b5e" />

### 2. Fetch Inference ✅

<img width="420" alt="Image" src="https://github.com/user-attachments/assets/1fb596c9-35d6-4516-bb79-2419e09e934b" />

---

I did notice something else though. The only thing that keeps becoming `never` in my code. it's related to if `c.json({ /* any object */ } | undefined)`.

For example:
```ts
.post("/")
const toReturn = { id: "123" } // <- when this is sometimes undefined.

response.json(toReturn); // The type will always infer to `never`

// But if I do this:

response.json(toReturn) // Then this type will return as { id: string }
```

**Comment by MathurAditya724** [comment]
Thanks @Blankeos for this, I will close this then.
